## Introduction to Numpy: Array-Oriented Programming ICA

#### Follow the prompts below to practice the concepts learned in the Introduction to Numpy: Array-Oriented Programming lecture. Submit the assignment as a .ipynb through blackboard.

In [9]:
import numpy as np

##### Prompt1
Set your random number generator seed to 2354 using the np.random.seed() command. Create a new variable called rarray with a 2 by 3 array with possible numbers from 0 to 100 using np.random.randint(). Print this array.

In [16]:
np.random.seed(2354)
rarray=np.random.randint(low=0, high=100, size=(2,3))
print(rarray)

[[68 56 26]
 [14 81 92]]


##### Prompt2
Sort rarray so that each row is in ascending order. Print your array to confirm your result.

In [17]:
rarray.sort()
rarray

array([[26, 56, 68],
       [14, 81, 92]])

##### Prompt3
Set your random number generator seed to 8563 and create a new variable called rarray2 with a 1 by 3 array with possible numbers from 0 to 100. Print this array.

In [19]:
np.random.seed(8563)
rarray2=np.random.randint(low=0, high=100, size=(1,3))
print(rarray2)

[[83 50 27]]


##### Prompt4
Use broadcasting to divide rarray by rarray2 and save the result as a variable called resarray. Print this array.

In [24]:
resarray=(rarray/rarray2)
print('divide rarray by rarray2: \n')
print(resarray)

divide rarray by rarray2: 

[[0.31325301 1.12       2.51851852]
 [0.1686747  1.62       3.40740741]]


##### Prompt5
Even though both arrays contain integers, what do you notice about the resulting array that supports pythons ability to convert between numeric types? Print the data types of your array to support your conclusion.

In [29]:
print(rarray.dtype)
print(rarray2.dtype)
print(resarray.dtype) 
#Python classify 'resarray' as a float

int32
int32
float64


##### Prompt6
Use for loops to iterate through the rows and columns of resarray and print each element. My solution (there may be others) used two for loops, a combination of range() and len(), and slicing to accomplish this task.

In [33]:
for value in range(0,len(resarray)):
    for value2 in range(0,len(resarray[value])):
        print(resarray[value][value2])



0.3132530120481928
1.12
2.5185185185185186
0.1686746987951807
1.62
3.4074074074074074


##### Prompt7
Calculate the sum of the rows of resarray and save it in a variable called sumarray. Print this array.

In [36]:
sumarray=(resarray.sum(axis=1))
print('the sum of the rows is: ')
print(sumarray)

the sum of the rows is: 
[3.95177153 5.19608211]


##### Prompt8
Broadcast sumarray over resarray to subtract each row sum from each element in that row. You will have to change the shape of sumarray, I used .reshape().

In [41]:
b_sum = sumarray.reshape(-1, 1)
resarray -= b_sum
print(resarray)

[[-3.63851852 -2.83177153 -1.43325301]
 [-5.02740741 -3.57608211 -1.7886747 ]]


##### Prompt9
Set your random number generator seed to 7245 and create a new variable called rarray3 with a 2 by 2 array with possible numbers from 0 to 100. Print this array. Then use the linalg library to get the inverse of this array. Print the result.

In [48]:
np.random.seed(7245)
rarray3=np.random.randint(low=0, high=100, size=(2,2))
print('new variable: \n',rarray3,'\n')
print('the inverse of rarray3: \n', np.linalg.inv(rarray3))

new variable: 
 [[ 0 28]
 [37 25]] 

the inverse of rarray3: 
 [[-0.02413127  0.02702703]
 [ 0.03571429  0.        ]]


##### Prompt10
Use np.where() to create a boolean array with 1's when the elements of resarray are greater than or equal to the overall mean of resarray and 0's when they are less than.

In [55]:
resarray=(rarray/rarray2)
mean_R=np.mean(resarray)
print('The mean is: \n', mean_R )
bool_array=np.where(resarray>=mean_R,1,0)
print('The boolean array is: \n', bool_array)

The mean is: 
 1.5246422727948834
The boolean array is: 
 [[0 0 1]
 [0 1 1]]
